version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql_container
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  flask1:
    build: .
    container_name: flask_container
    image: flask_container
    ports:
      - "5000:5000"
    environment:
        - MESSAGE=Hello from Flask1
        - DB=mysql
        - DB_NAME=test_db
        - DB_PARAMS=host=localhost,port=3306,user=root,password=rootpassword
    volumes:
      - .:/app
    depends_on:
      - mysql
      - mongodb
      - redis

  flask2:
    build: .
    container_name: flask_container2
    image: flask_container
    ports:
      - "5001:5000"
    environment:
        - MESSAGE=Hello from Flask2
        - DB=mongodb
        - DB_NAME=test_db
        - DB_PARAMS=target=test,user=root,password=rootpassword
    volumes:
      - .:/app
    depends_on:
      - mysql
      - mongodb
      - redis

  flask3:
    build: .
    container_name: flask_container3
    image: flask_container
    ports:
      - "5002:5000"
    environment:
        - MESSAGE=Hello from Flask3
        - DB=redis
        - DB_NAME=0
        - DB_PARAMS=host=localhost,port=6379
    volumes:
      - .:/app
    depends_on:
      - mysql
      - mongodb
      - redis


volumes:
  mysql_data:
  mongo_data:
  redis_data: